version: "2.3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: agroimpacts/labeller
    ports:
      - 9090:9090
    command:
      - --http
      - :9090
      - --wsgi-file
      - "getkml.wsgi"