labeller:
  DEBUG: true
  ## initial
  ## 1 for initial sites across the whole study area
  ## 2 for single independent labelling
  ## 3 for regular mode
  initial: true
  MAIL_PASSWORD:
  MAIL_PORT: 25
  MAIL_SERVER: localhost
  MAIL_USERNAME:
  MAIL_USE_SSL:
  MAIL_USE_TLS:
  PL_API_KEY: 
  SECRET_KEY: 
  bing_key: 
  mapbox_key: 
  slack_url: 
  # AWS bucket for key inputs/outputs
  bucket: 
  # define HIT/kml type for loading initial sites
  kml_type: 
  sites: 
  reset_initial: False
  n: 500  # number of F sites to draw at random from main grid
  aws_access: 
  aws_region: us-east-1
  aws_secret: 
  consensus_directory: /labels/ghana/
  consensus_heatmap_dir: heatmaps/ghana
  consensus_riskmap_dir:
  db_host: labeller.crowdmapper.org
  db_password: 
  db_pgpassword:
  db_production_name: Africa
  db_url:
  db_username: 
  aoi_s3_object: grid/image_target_aois.geojson
  master_grid_s3_object: grid/master_grid.tif
  s3_catalog_name: planet_catalog_ghana_full.csv
  # This url is the slack app webhooks url to send notification
  slack_url:
  # Set last name filter for the noticification.
  notification_filter: ["Song", "Estes"]
  github_repo: agroimpacts/issues
  github_token: 
  mapping_category1: field
  mapping_category2:
  mapping_category3:
